spring.application.name=musiclab
#spring.datasource.url=jdbc:mysql://localhost:3306/db_musiclab?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=

# Conexi\u00f3n local
#spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:11269/railway
# Conexi\u00f3n remota
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway

spring.datasource.username=root
spring.datasource.password=gfAQHRduUpNrNZRHarHgvfDItlgZeXLM
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
springdoc.swagger-ui.path=/swagger

# Limite de tama\u00f1o de archivos
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Permitir conexi\u00f3n
server.port=${PORT:8080}
server.address=0.0.0.0

# a\u00f1adido al instalar spring-boot-starter-security
spring.main.allow-bean-definition-overriding=true
# prueba de definir usuario (no funciona si definimos usuarios en WebSecurityConfig)
spring.security.user.name=test
spring.security.user.password=1234
# para que me cree las tablas cada vez que arranco la API
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

# Modo desarrollo
#spring.profiles.active=dev

# Google OAuth
google.oauth.client-id=481714463254-e911fa9mf7q3tojndep80dvc853htl2c.apps.googleusercontent.com
