spring.application.name=musiclab
# Conexi\u00f3n remota
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}

spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
springdoc.swagger-ui.path=/swagger

# Limite de tama\u00f1o de archivos
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Permitir conexi\u00f3n
server.port=${PORT:8080}
server.address=0.0.0.0

# a\u00f1adido al instalar spring-boot-starter-security
spring.main.allow-bean-definition-overriding=true

# para que me cree las tablas cada vez que arranco la API
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

# Modo desarrollo
#spring.profiles.active=dev

# Google OAuth
google.oauth.client-id=${GOOGLE_CLIENT_ID}
